name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: apt install
      run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            protobuf-compiler \
            libprotobuf-dev \
            qtbase5-dev \
            libqt5opengl5-dev \
            g++ \
            libusb-1.0-0-dev \
            libsdl2-dev \
            libqt5svg5-dev \
            libssl-dev
    - name: cmake
      run: |
          mkdir -p build 
          cd build 
          cmake .. 
    - name: make
      run: | 
          cd build
          make -j 4 simulator-cli
    - name: clean
      run: |
        mv build/bin .
        rm -rf $(ls | grep -vE '^(config|bin)$')
        cd ../..
    - name: ls
      run: |
          pwd
          ls
    - name: tar
      run: |
          cd ..
          tar zcvf framework.tar.gz framework
    - name: Create Release
      run: gh release create latest framework.tar.gz
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
